### ISSUE TITLE
Role of <Route>

### ISSUE THREAD

**Issue by estudovt** [chartickceo/react-app-boilerplate#3]
Explain the role of the exact prop in the <Route> component for the Home page (<Route path="/" exact component={Home} />). What happens if you remove it?

**Comment by feyuk** [comment]
The exact prop ensures that the specified component is rendered only when the path exactly matches the defined path. In this case, without the exact prop, the Home component would be rendered not only for the path '/' but also for any other path that starts with '/' (e.g., '/about', '/contact', etc.). By adding exact, it restricts the rendering to the exact path match, ensuring that the Home component is only rendered for the root path.
